config/routes.rb
Rails.application.routes.draw do
  resources :categories

  
  
  devise_for :users, controllers: {registrations: 'registrations'}
  # devise_scope :users do
  #   get "user/:id/edit" => "registrations#editprofile"
  # end 
  # get 'user/:id', to: 'registrations#showprofile', as:'show_user'
  # get 'user/:id/edit', to: 'registrations#editprofile', as:'edit_user'
  resources :products
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  # root "welcomes#index"
  get 'category/:id', to: 'products#showproducts', as: 'cat'
  get 'category', to: 'categories#testing', as: 'testcat'
  #get 'buy/:id', to: 'categories#buy', as:'buy'
  get 'purchase', to: 'purchases#index', as:'purchase'
  get 'user/:id', to: 'purchases#showprofile', as:'show_user'
  get 'user/:id/edit', to: 'purchases#editprofile', as:'edit_user'
  get 'allproducts', to: 'products#show_all_products', as:'all_products'
  # put 'user/:id', to: 'purchases#update'
  patch 'user/:id', to: 'purchases#update'
  get 'success/:id', to: 'products#success', as:'success'
  resources :charges
  
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def testing
    
  end

  def buy
    redirect_to new_charge_path
     # OrderItem.where(order_id: params[:id]).each do |prod|
     # prod.update_attribute :status, "Pdd"
     # end
     # session[:order_id]=nil
     # redirect_to root_path
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :detail)
    end
end

app/helpers/categories_helper.rb
# Module Categories Helper

module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.detail %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @category.detail %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/testing.html.erb
<table class="table">

  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Item Name</th>
      <th></th>
      <th>Unit Price</th>
      <th>Quantity</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
  		<% current_order.order_items.each do |bill| %>
        <tr>
          <th scope="row">1</th>
          <td><%= bill.product.name %></td>
          <td><img class="billimage" src="<%= bill.product.image.url %>" alt="Image not Available"></td>
          <td><%= bill.unit_price %></td>
          <td><%= bill.quantity %></td>
          <td><%= bill.total_price %></td>
        </tr>
      <% end %>
      <tr>
        <th colspan = 5>Grand Total</th>
        <td> <%= current_order.subtotal %></td>
      </tr>
  </tbody>
</table>
<%= link_to 'buy', success_path(current_order.id),  class: "btn btn-default btn-success" %>