config/routes.rb
Rails.application.routes.draw do
  resources :categories

  
  
  devise_for :users, controllers: {registrations: 'registrations'}
  # devise_scope :users do
  #   get "user/:id/edit" => "registrations#editprofile"
  # end 
  # get 'user/:id', to: 'registrations#showprofile', as:'show_user'
  # get 'user/:id/edit', to: 'registrations#editprofile', as:'edit_user'
  resources :products
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  # root "welcomes#index"
  get 'category/:id', to: 'products#showproducts', as: 'cat'
  get 'category', to: 'categories#testing', as: 'testcat'
  #get 'buy/:id', to: 'categories#buy', as:'buy'
  get 'purchase', to: 'purchases#index', as:'purchase'
  get 'user/:id', to: 'purchases#showprofile', as:'show_user'
  get 'user/:id/edit', to: 'purchases#editprofile', as:'edit_user'
  get 'allproducts', to: 'products#show_all_products', as:'all_products'
  # put 'user/:id', to: 'purchases#update'
  patch 'user/:id', to: 'purchases#update'
  get 'success/:id', to: 'products#success', as:'success'
  resources :charges
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  mount_uploader :image, ImageUploader
  default_scope { where(active: true) }


  # include ActiveModel::AttributeMethods

  # attr_accessor :avialable_quantity, :status, :active

  # private
  #   def reset_attribute(attribute)
  #     send("#{attribute}=", false)
  #   end
 
  #   def attribute_any?(attribute)
  #     send(attribute) < 1
  #   end

  #   def redefine_attribute(attribute)
  #     send("#{attribute}=", "Out of Stock")
  #   end
  # before_commit :product_available
  # validate :product_check

  # def product_available
  # 	if product.avialable_quantity < 1
  # 	  product.update_attributes(active: false)
  # 	end
  # end

  # def product_check
  # 	if !product.active?
  #     errors.add(:product, "is not valid or is not active.")
  #   end
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_availability

  def check_availability
    Product.all.each do |prod|
      if prod.avialable_quantity.to_i < 1 
        prod.update_attributes(active: false)
      end
    end  
  end
  def error
    redirect_to root_path
  end
  def index
  	@products = Product.all
    @order_item = current_order.order_items.new
  end

  def new
    authorize! :manage, :all
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
     authorize! :manage, :all
    @product = Product.find(params[:id])
  end

  def success
    @product=OrderItem.where(order_id: params[:id])
    @product.each do |prod|
      quan=prod.product.avialable_quantity.to_i-prod.quantity
      if quan < 0
        flash[:notice] = "Insufficient Stock"
        break
      end
      prod.product.update_attributes(avialable_quantity: quan)  
      prod.update_attributes(status: "Purchased")
    end
    session[:order_id]=nil
    redirect_to root_path
  end

  def show_all_products
    authorize! :manage, :all
    @all_products=Product.all
  end

  def show
  	@product=Product.where(id: params[:id])
    @order_item = current_order.order_items.new
  end

  def showproducts
    @product=Product.where(category_id: params[:id])
    @order_item = current_order.order_items.new
  end
  # POST /products
  # POST /products.json
  def create
    authorize! :manage, :all
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product detail was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize! :manage, :all
    respond_to do |format|
  
      @product = Product.find(params[:id])
      if @product.update(product_params)

        format.html { redirect_to @product, notice: 'Product detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    byebug
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def product_params
      params.require(:product).permit(:category_id, :name, :seller, :best_before_date, 
        :manufacture_date, :details, :brand, :status, :image,
        :price, :avialable_quantity, :discount, :product_code)
    end
end

app/helpers/products_helper.rb
#Module Products Helper
module ProductsHelper
	
	def categories
		Category.all
	end

end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this @product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.collection_select(:category_id, categories, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :manufacture_date %>
    <%= f.text_field :manufacture_date,  'data-provide' => 'datepicker' %>
  </div>

  <div class="field">
    <%= f.label :best_before_date %>
    <%= f.text_field :best_before_date,  'data-provide' => 'datepicker' %>
  </div>

  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>

  <div class="field">
    <%= f.label "Brand (if any)" %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :avialable_quantity %>
    <%= f.text_field :avialable_quantity %>
  </div>

  <div class="field">
    <%= f.label :discount %>
    <%= f.number_field :discount %>
  </div>

  <div class="field">
    <%= f.label :product_code %>
    <%= f.text_field :product_code %>
  </div>
  
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<div class="card" style="width: 20rem;">
  <% if can? :edit, Product%>
    <%= link_to 'Edit', edit_product_path(product.id) %>
  <% end %>
  <img class="card-img-top" src="<%= product.image.url %>" alt="Card image cap">
  <%= form_for order_item, remote: true do |f| %>
  <div class="card-block">
    <h4 class="card-title" >Price: <span style="color: green"><%=  product.price %></span></h4>
    <h4 class="card-title"><%= link_to product.name ,product_path(product.id) %></h4>
      <%= f.hidden_field :product_id, value: product.id %>
        <% if user_signed_in? %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        <% end %>
    <div class="input-group">
      <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
    </div>
    <div class="input-group-btn">
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
    </div>        
  </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h2> Edit </h1>
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  
</div>

app/views/products/new.html.erb
<h1>New Product Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
  
    <% @product.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  
</div>
<h3> <p class="card-text"><%= @product.first.details %></p> </div>

app/views/products/show_all_products.html.erb
	<table border=3>
		<tr>
			<td align="center"> Product ID </td>
			<td align="center"> Name </td>
			<td align="center"> Price </td>
			<td align="center"> Manufacture Date </td>
			<td align="center"> Best Before Date </td>
			<td align="center"> Details </td>
			<td align="center"> Brand </td>
			<td align="center"> Status </td>
			<td align="center"> available quantity </td>
			<td align="center"> Product Code </td>
			<td align="center"> Image </td>
			<td align="center">Active/Not</td>
			<td align="center"></td>
			<td align="center"></td>

		</tr>
		<% @all_products.each do |prod| %>
			<tr align='center'>
				<td align="center"> <%= prod.id %> </td>
				<td align="center"> <%= prod.name%> </td>
				<td align="center"> <%= prod.price%> </td>
				<td align="center"><%= prod.manufacture_date%> </td>
				<td align="center"><%= prod.best_before_date%> </td>
				<td align="center"><%= prod.details%> </td>
				<td align="center"> <%= prod.brand%> </td>
				<td align="center"> <%= prod.status%> </td>
				<td align="center"><%= prod.avialable_quantity%> </td>
				<td align="center"><%= prod.product_code%> </td>
				<td align="center"><img class = "smallimg" src="<%= prod.image.url %>" alt="Card image cap"></td>
				<td align="center"><%= prod.active %></td>
				<td align="center"><%= link_to 'Edit', edit_product_path(prod.id) %> </td>
				<td align="center"><%= link_to 'Show', product_path(prod.id) %> </td>
			</tr>
			<% end %>

	</table>

app/views/products/showproducts.html.erb
<div class="row">
  
    <% @product.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  
</div>