config/routes.rb
Rails.application.routes.draw do
  resources :categories

  
  
  devise_for :users, controllers: {registrations: 'registrations'}
  # devise_scope :users do
  #   get "user/:id/edit" => "registrations#editprofile"
  # end 
  # get 'user/:id', to: 'registrations#showprofile', as:'show_user'
  # get 'user/:id/edit', to: 'registrations#editprofile', as:'edit_user'
  resources :products
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  # root "welcomes#index"
  get 'category/:id', to: 'products#showproducts', as: 'cat'
  get 'category', to: 'categories#testing', as: 'testcat'
  #get 'buy/:id', to: 'categories#buy', as:'buy'
  get 'purchase', to: 'purchases#index', as:'purchase'
  get 'user/:id', to: 'purchases#showprofile', as:'show_user'
  get 'user/:id/edit', to: 'purchases#editprofile', as:'edit_user'
  get 'allproducts', to: 'products#show_all_products', as:'all_products'
  # put 'user/:id', to: 'purchases#update'
  patch 'user/:id', to: 'purchases#update'
  get 'success/:id', to: 'products#success', as:'success'
  resources :charges
  
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{ current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_mainpage.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', root_path %>
        </li>
      </ul>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if can? :create, Product%>
          <li>
            <%= link_to 'New Product', new_product_path %>
          </li>
          <li>
            <%= link_to 'New Category', new_category_path %>
          </li>
          <li>
            <%= link_to 'All Products', all_products_path %>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories 
            <span class="caret">
            </span>
          </a>
          <ul class="dropdown-menu">
            <% categories.each do |cat| %>
              <li><%= link_to cat.name, cat_path(cat.id) %> </a></li>
            <% end %>
          </ul>
        </li>
        
      </ul>
     <!--  <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->
        <ul class="nav navbar-nav navbar-right">
          <li><% if !user_signed_in? %>
            <li>
              <%= link_to('Login', new_user_session_path)  %>  
            </li>
            <% end %>
          </li>
          <li class="cart-text"><%= link_to "#{current_order.order_items.size} Items in Cart ( #{ current_order.subtotal} )", cart_path, class: "btn btn-link" %> </li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %>
                  <span class="caret">
                  </span>
                </a>
                <ul class="dropdown-menu">
                  <% if user_signed_in? %>
                    <li>  
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                    </li>
                    <li> 
                      <%= link_to('Purchase History', purchase_path) %> 
                    </li>
                    <li>
                      <%= link_to('Profile', show_user_path(current_user.id)) %>
                    </li>
                  </ul>
                </li>
              <% end %>
            <% end %>
          </li>
        </ul><!-- /.navbar-collapse -->
      </form><!-- /.container-fluid -->
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCartExample</title>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>
  </head>
  <body>
      <%= render 'layouts/mainpage' %>

    <div class="container">
      <hr>
      <%= flash[:notice] %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>